# Generated by Django 4.0.3 on 2022-04-17 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crypto_app', '0003_crypto_curr_n_alter_crypto_curr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='curr_n',
        ),
    ]
