# Generated by Django 4.0.3 on 2022-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crypto_app', '0007_alter_crypto_curr_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='curr_n',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollars'), ('UAH', 'Hryvna'), ('GBP', 'GBP')],
                                   default='R', max_length=3),
        ),
    ]
