# Generated by Django 4.0.3 on 2022-04-17 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crypto_app', '0011_crypto_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='currency',
        ),
    ]
